name: Construire AdminIA Android

on:
  workflow_dispatch: # Permet de lancer le build à la main
  push:
    branches:
      - main # Lance un build automatiquement si tu pousses une modification sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupérer le code du dépôt
        uses: actions/checkout@v3

      - name: 🟢 Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Installer EAS CLI
        run: npm install -g eas-cli

      - name: 🔑 Connexion à Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Générer APK (mode test - preview)
        run: eas build --platform android --profile preview --non-interactive

      - name: 🚀 Générer AAB (mode production - Play Store)
        run: eas build --platform android --profile production --non-interactive
